// User
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SET_USER_INFO = "SET_USER_INFO";
export const START_LOADING_USER_INFO = "START_LOADING_USER_INFO";
export const END_LOADING_USER_INFO = "END_LOADING_USER_INFO";
export const LOGOUT = 'LOGOUT';
// LK settings
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_MENU_TYPE = "CHANGE_MENU_TYPE";
// Snackbar
export const HANDLE_SNACKBAR = "HANDLE_SNACKBAR";
// Payments
export const SET_PAYMENTS_FIELDS = "SET_PAYMENTS_FIELDS"; 
export const LOADING_PAYMENTS_FIELDS = "LOADING_PAYMENTS_FIELDS"; 
export const CHANGE_PRECHECK_INFO = "CHANGE_PRECHECK_INFO";
export const LOADING_PRECHECK_BLOCK = "LOADING_PRECHECK_BLOCK";